dashboard/dash/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboard.dash import views

app_name = 'dash'
urlpatterns = [
    path('', views.dash, name='index'),

]

dashboard/subs/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboard.subs import views

app_name = 'subs'
urlpatterns = [
    path('', views.subscriptions, name='index'),
    path('new/', views.subscription_form, name='sub_form'),
    path('add/', views.add_subscription, name='sub_add'),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboard.dash import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.dash.urls')),
    path('subs/', include('dashboard.subs.urls')),
    path('wishlist/', include('dashboard.wishlist.urls'))
]

dashboard/wishlist/urls.py
from django.contrib import admin
from django.urls import include, path
from dashboard.wishlist import views

app_name = 'wishlist'
urlpatterns = [
    path('', views.wishlist, name='index'),
]

dashboard/dash/models.py
from django.db import models
from enum import Enum


class PeriodChoice(Enum):
    DAILY = "Daily"
    WEEKLY = "Weekly"
    MONTHLY = "Monthly"
    YEARLY = "Yearly"
    
    def __str__(self):
        return str(self.value)


class PaymentChoice(Enum):
    CASH = "Cash"
    CC = "Credit Card"
    
    def __str__(self):
        return str(self.value)



class Label(models.Model):
    name = models.CharField(max_length=10)
    description = models.CharField(max_length=100)
    colour = models.CharField(max_length=6)

    def __str__(self):
        return self.name

 

dashboard/subs/models.py
from django.db import models
from django.contrib.auth.models import User
from dashboard.dash.models import PeriodChoice
from dashboard.dash.models import PaymentChoice
from dashboard.dash.models import Label

class Subscription(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100)
    price = models.FloatField()
    currency = models.CharField(max_length=3)
    recurring = models.BooleanField()
    start_date = models.DateField()
    recurring_period = models.SmallIntegerField()
    recurring_unit = models.CharField(max_length=10, choices=[(tag, tag.value) for tag in PeriodChoice])
    payment_method = models.CharField(max_length=10, choices=[(tag, tag.value) for tag in PaymentChoice])
    labels = models.CharField(max_length=100)

    def __str__(self):
        return self.name

dashboard/wishlist/models.py
from django.db import models

# Create your models here.

dashboard/subs/forms.py
from django import forms
from django.conf import settings
from django.forms import ModelForm
from dashboard.dash.models import PeriodChoice
from dashboard.dash.models import PaymentChoice
from dashboard.subs.models import Subscription



class SubscriptionForm(ModelForm):
    description = forms.CharField(widget=forms.Textarea)
    start_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    
    class Meta:
        model = Subscription
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.keys():            
            self.fields[field].widget.attrs.update({'class': 'form-control'})
    
    
    def clean(self):
        self.recurring_unit = str(self.cleaned_data['recurring_unit'])
        self.payment_method = str(self.cleaned_data['payment_method'])

dashboard/dash/views.py
from django.shortcuts import render
from django.http import Http404
from django.shortcuts import render

def dash(request):
    return render(request, 'dash/dash.html')

dashboard/subs/views.py
from django.http import Http404
from django.shortcuts import render
from dashboard.subs.models import Subscription
from dashboard.subs.forms import SubscriptionForm


def subscriptions(request):
    payload = {}
    if request.user:
        payload.update(subscrptions = Subscription.objects.all())
        return render(request, 'subs/subs.html', payload)
    
    
def subscription_form(request):
    payload = {}
    form = SubscriptionForm()
    payload.update(form = form )
    return render(request, 'subs/addSub.html', payload)


def add_subscription(request):
    payload = {}
    form = SubscriptionForm(request.POST)
    form.save()
    payload.update(form = SubscriptionForm())
    return render(request, 'subs/addSub.html', payload)

dashboard/wishlist/views.py
from django.http import Http404
from django.shortcuts import render
from dashboard.subs.models import Subscription
from dashboard.subs.forms import SubscriptionForm


def wishlist(request):
    payload = {}
    return render(request, 'wishlist/wishlist.html', payload)

dashboard/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
<link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
<link href={% static "css/dashboard.css" %} rel="stylesheet">

    <!-- Favicons -->

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'dash:index' %}">Dashboard</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign In</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        {% block sidebar %}
          {% include "sidebar.html" %}
        {% endblock %}
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
      {% block content %}

      {% endblock %}
</div>
    </main>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src={% static "js/bootstrap.bundle.min.js" %} integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
</body>
</html>

dashboard/templates/dash/dash.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}

{% block content %}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
            This week
          </button>
        </div>
      </div>

{% endblock %}

dashboard/templates/sidebar.html
<ul class="nav flex-column">
    <li class="nav-item">
    <a class="nav-link" href="{% url 'subs:index' %}">
        <span data-feather="file"></span>
        Subscriptions
    </a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="#">
        <span data-feather="shopping-cart"></span>
        Wishlist
    </a>
    </li>

</ul>

dashboard/templates/subs/addSub.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %} {% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">New Subscription</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
        </div>
    </div>
</div>


<div class="container">
    <table class="table table-striped">
        <tbody>
            <form method="post" class="well form-horizontal" action="{% url 'subs:sub_add' %}">
                {% csrf_token %}
                <tr>
                    <td colspan="1">
                        {% for field in form %}
                        <div class="form-group">
                            <label class="col-md-4 control-label"> {{ field.label_tag }} </label>
                            <div class="col-md-8 inputGroupContainer">{{ field }}</div>
                            <small id="help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                            <small id="error" class="form-text text-muted"> {{ field.errors }}</small>
                        </div>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td colspan="1"><button type="submit" class="btn btn-dark">Add New</button></td>
                </tr>
            </form>
        </tbody>
    </table>
</div>
{% endblock %}

dashboard/templates/subs/subs.html
{% extends "base.html" %}

{% block title %}Subscriptions{% endblock %}

{% block content %}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Subscriptions</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
              <a href="{% url 'subs:sub_form' %}" class="btn btn-outline-success" role="button" aria-pressed="true">New</a>
          </div>
        </div>
      </div>

    <div class="list-group">
        {% for sub in subscriptions %}
            <a href="#" class="list-group-item list-group-item-action">{{sub.name}}</a>
        {% endfor %}
        <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-primary">This is a primary list group item</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-secondary">This is a secondary list group item</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-success">This is a success list group item</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-danger">This is a danger list group item</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-warning">This is a warning list group item</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-info">This is a info list group item</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-light">This is a light list group item</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-dark">This is a dark list group item</a>
    </div>
{% endblock %}

dashboard/templates/wishlist/wishlist.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
         </div>
        </div>
      </div>

{% endblock %}